services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VARIANT=${PHP_VERSION}-${DEBIAN_VERSION}
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - mysql
      - pgsql

  mysql:
    image: ${MYSQL_IMAGE}:${MYSQL_VERSION}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_IMAGE: ${MYSQL_IMAGE}
    volumes:
      - mysql-data:/var/lib/mysql
      - ../sql/pdns/${PDNS_BRANCH}/schema.mysql.sql:/docker-entrypoint-initdb.d/init.sql
      - ./custom-healthcheck.sh:/custom-healthcheck.sh
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "/custom-healthcheck.sh"]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3

  pgsql:
    image: ${PGSQL_IMAGE}:${PGSQL_VERSION}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgsql-data:/var/lib/postgresql/data
      - ../sql/pdns/${PDNS_BRANCH}/schema.pgsql.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  dns:
    image: powerdns/pdns-auth-${PDNS_BRANCH}:${PDNS_VERSION}
    volumes:
      - ./pdns.conf:/etc/powerdns/pdns.conf
    ports:
      - "1053:53"
      - "1053:53/udp"
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql-data: { }
  pgsql-data: { }
